# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Save artifacts
inputs:
  directory:
    type: string
    description: Path of the directory to save
runs:
  using: composite
  steps:
    - run: |
        tar cvf artifact.tar ${{ inputs.directory }}
        mv artifact.tar artifact-$(sha1sum artifact.tar|awk '{ print $1 }').tar
        echo NAME=$(echo artifact-*.tar) >> $GITHUB_OUTPUT
      shell: bash
      id: tar
    - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: ${{ steps.tar.outputs.NAME }}
        path: artifact-*.tar
