# Tar is used because the default actions do not preserve directory structure
# and file mode.
name: Save artifacts
inputs:
  directory:
    type: string
    description: Path of the directory to save
runs:
  using: composite
  steps:
    - run: |
        tar cvf artifact.tar ${{ inputs.directory }}
        mv artifact.tar artifact-$(sha1sum artifact.tar|awk '{ print $1 }').tar
        echo NAME=$(echo artifact-*.tar) >> $GITHUB_OUTPUT
      shell: bash
      id: tar
    - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{ steps.tar.outputs.NAME }}
        path: artifact-*.tar
